apiVersion: v1
kind: Pod
metadata:
  name: s3-access-pod
  namespace: default
spec:
  serviceAccountName: s3-access
  containers:
  - name: aws-cli-container
    image: amazon/aws-cli:latest
    command: ["sh", "-c", "aws s3 ls s3://<BUCKET-NAME>"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
